name: FasterARK
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
env:
  PSPDEV: /usr/local/pspdev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Dependencies
        run: |
          sudo apt-get install git openssh-client clang automake autoconf zlib1g-dev python3 python3-pycryptodome python3-ecdsa p7zip-full curl unzip sudo mkisofs

      - name: Getting lastest pspdev
        run: |
          curl -OJL 'https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz'
          sudo tar xvf pspdev-ubuntu-latest-x86_64.tar.gz -C /usr/local/
          echo $PSPDEV/bin >> $GITHUB_PATH
          echo PATH="$PATH:$PSPDEV/bin"

      - name: Cloning and Building lastest pspsdk
        run: |
          git clone https://github.com/pspdev/pspsdk

      - name: Bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: ya2d via psp-pacman
        run: |
          psp-pacman -Syyu --noconfirm
          psp-pacman -S ya2d --noconfirm

      - name: Update psp-cfw-sdk
        run: curl -OJL "https://github.com/pspdev/psp-cfw-sdk/releases/download/latest/psp-cfw-sdk.zip"

      - name: Extract psp-cfw-sdk
        run: sudo unzip -o psp-cfw-sdk.zip -d /

      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Clone VitaSDK
        run: |
          git clone https://github.com/vitasdk/vdpm

      - name: Bootstrap VitaSDK
        working-directory: vdpm
        run: |
          ./bootstrap-vitasdk.sh
          echo VITASDK=/usr/local/vitasdk >> $GITHUB_ENV
          echo PATH=$VITASDK/bin:$PATH >> $GITHUB_ENV
          export VITASDK=/usr/local/vitasdk
          export PATH=$VITASDK/bin:$PATH
          ./install-all.sh

      - name: mkpsxiso
        run: |
          curl -OJL 'https://github.com/Lameguy64/mkpsxiso/releases/download/v2.20/mkpsxiso-2.20-Linux.deb'
          sudo apt-get install ./mkpsxiso-2.20-Linux.deb

      - name: Build
        run: make clean && make

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: FasterARK-release
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v8
        with:
          name: FasterARK-release
          path: dist/*.zip
      - name:
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: FasterARK
          prerelease: false
          make_latest: true
          files: |
            **/*.zip
            **/*.vpk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
