name: fastersoryn
on:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write
env:
  PSPDEV: /usr/local/pspdev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dependencies
        run: |
          sudo apt-get install -y git openssh-client clang automake autoconf zlib1g-dev python3 python3-pycryptodome python3-ecdsa p7zip-full curl unzip sudo mkisofs

      - name: getting lastest pspdev
        run: |
          curl -OJL 'https://github.com/pspdev/pspdev/releases/latest/download/pspdev-ubuntu-latest-x86_64.tar.gz'
          sudo tar xvf pspdev-ubuntu-latest-x86_64.tar.gz -C /usr/local/
          echo "$PSPDEV/bin" >> $GITHUB_PATH

      - name: cloning and building lastest pspsdk
        run: |
          git clone https://github.com/pspdev/pspsdk

      - name: bootstrap sdk and build
        working-directory: pspsdk
        run: |
          bash ./bootstrap
          ./configure
          make
          make install

      - name: build ya2d from source
        run: |
          git clone --depth 1 https://github.com/pspdev/psp-packages.git
          cd psp-packages
          ./build.sh --install ya2d

      - name: update psp-cfw-sdk
        run: curl -OJL "https://github.com/pspdev/psp-cfw-sdk/releases/download/latest/psp-cfw-sdk.zip"

      - name: extract psp-cfw-sdk
        run: sudo unzip -o psp-cfw-sdk.zip -d /

      - name: checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: build
        run: make clean && make

      - name: upload
        uses: actions/upload-artifact@v7
        with:
          name: fastersoryn-release
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v8
        with:
          name: fastersoryn-release
          path: dist/
      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          name: fastersoryn
          prerelease: false
          make_latest: true
          files: |
            **/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
